### ISSUE TITLE
Load Moodle's config file from puppet before running install_database.php

### ISSUE THREAD

**Issue by kwiliarty** [mackensen/moodle-hat#12]
We should revert #9 and just make sure that we load the `config.php` from puppet before running `admin/cli/install_database.php` as an alternative to `admin/cli/install.php`. The former expects `config.php` to exist, and by loading the config from puppet we keep the door open to tweak config settings down the road.

**Comment by mackensen** [comment]
@kwiliarty config.php isn't touched after creation now; can this issue be closed?

**Comment by kwiliarty** [comment]
Yes. Thanks.
