### ISSUE TITLE
Composer installation fails intermittently

### ISSUE THREAD

**Issue by mackensen** [mackensen/moodle-hat#20]
Hadn't seen this before:

```
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'The HOME or COMPOSER_HOME environment variable must be set for composer to install correctly'
```

I don't know why this is a problem now when it wasn't before, but setting `COMPOSER_HOME` as an environment variable is a trivial fix.

**Comment by infojasyrc** [comment]
I have the same issue working with vagrant and puppet to install composer.
