### ISSUE TITLE
Behat init problem

### ISSUE THREAD

**Issue by mosolov** [mackensen/moodle-hat#24]
==> default: Error: php admin/tool/behat/cli/init.php returned 250 instead of one of [0]
==> default: Error: /Stage[main]/Moodle::Behat/Exec[configure_behat]/returns: change from notrun to 0 failed: php admin/tool/behat/cli/init.php returned 250 instead of one of [0]

OS: OS X
Vagrant vers.: 1.8.1

**Comment by mackensen** [comment]
If I had to guess this is related to #22, but I need more information. Could you please uncomment the puppet debug line in the Vagrantfile and re-run the provisioner?

**Comment by mackensen** [comment]
Reproduced:

```
==> default: Notice: /Stage[main]/Moodle::Behat/Exec[configure_behat]/returns: Generating autoload files
==> default: Notice: /Stage[main]/Moodle::Behat/Exec[configure_behat]/returns: Error: $CFG->behat_dataroot, $CFG->behat_prefix and $CFG->behat_wwwroot need to be set in config.php.
==> default: Notice: /Stage[main]/Moodle::Behat/Exec[configure_behat]/returns: 
==> default: Notice: /Stage[main]/Moodle::Behat/Exec[configure_behat]/returns: Ensure you set $CFG->behat_* vars in config.php and you ran admin/tool/behat/cli/init.php.
==> default: Notice: /Stage[main]/Moodle::Behat/Exec[configure_behat]/returns: More info in http://docs.moodle.org/dev/Acceptance_testing#Installation
==> default: Error: php admin/tool/behat/cli/init.php returned 250 instead of one of [0]
```

**Comment by mosolov** [comment]
Thx! Will I have issues with these warnings?

==> default: Warning: Could not retrieve fact fqdn
==> default: Warning: Host is missing hostname and/or domain: moodlehat
==> default: Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
==> default: Warning: Scope(Concat::Fragment[Apache ports header]): The $ensure parameter to concat::fragment is deprecated and has no effect.
==> default: Warning: Scope(Concat::Fragment[Listen 80]): The $ensure parameter to concat::fragment is deprecated and has no effect.

**Comment by mackensen** [comment]
No, those are all normal and expected (and not specific to this project).
