### ISSUE TITLE
Configure cron by default

### ISSUE THREAD

**Issue by mackensen** [mackensen/moodle-hat#33]
What it says on the tin. Useful for running scheduled tasks. I'm thinking about adding it, but commenting it out by default. I can see use cases for when you wouldn't want it running while you were actively developing a new task.

**Comment by mackensen** [comment]
I'm thinking as part of this I might create another vhost, `cron.moodle.dev`, to expose the cron logs, instead of just sending them to /dev/null.

**Comment by kwiliarty** [comment]
That's a great idea and moves it beyond the realm of something that would be easy to do manually.
