### ISSUE TITLE
Replace *.dev with *.localdomain

### ISSUE THREAD

**Issue by mackensen** [mackensen/moodle-hat#45]
See [Chrome to force .dev domains to HTTPS via preloaded HSTS](https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/); *.dev hosts are going to become troublesome under Chrome.

**Comment by mackensen** [comment]
The consensus at the [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/583) project was `.test`.

**Comment by tomjn** [comment]
`.localhost` according to the RFC can only reference the local loopback, so it wouldn't work across local networks

`.local` has issues when it conflicts with bonjour and zeroconf

`.test` is reserved for testing, and can be used however we see fit, so it's safe
